dataset:
    train:
        name: GOPRO_rearrange
        mode: train
        
        sampling: n_c  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: True
        interval: 1
        
        root_gt: "/ssd/0/zzh/dataset/GoPro/GoPRO_INR/GoPro_train_sharp_resized_cropped/"
        root_input: "/ssd/0/zzh/dataset/GoPro/GoPRO_INR/GoPro_train_blur_gamma_ratio_5_steps_20000_dec/"
        data_type: "imgs"
        num_frames: 5
        
        # augmentations
        augmentation:
            RandomCrop: 
                size : [128, 128] # zzh: [256, 256]
            RandomHorizontalFlip: 
                p: 0.5
            RandomVerticalFlip: 
                p: 0.5
            RandomRotation90: 
                p: 0.5
            # RandomReverse: 
            #     p: 0.5
        # dataloader per GPU
        loader:
            batch_size: 8
            num_workers: 8
            

    val:
        name: GOPRO_rearrange
        mode: val
        
        sampling: n_c  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: True
        interval: 1
        
        root_gt: "/ssd/0/zzh/dataset/GoPro/GoPRO_INR/GoPro_test_sharp_resized_cropped/"
        root_input: "/ssd/0/zzh/dataset/GoPro/GoPRO_INR/GoPro_test_blur_gamma_ratio_5_steps_20000_dec/"
        data_type: "imgs"
        num_frames: 5

        loader:
            batch_size: 1
            num_workers: 1
    
    test:
        name: GOPRO_rearrange
        mode: val
        
        sampling: n_c  # "n_n" and "n_c" , "n_l", "n_r"
        overlapping: True
        interval: 1
        
        root_gt: "/ssd/0/zzh/dataset/GoPro/GoPRO_INR/GoPro_test_sharp_resized_cropped/"
        root_input: "/ssd/0/zzh/dataset/GoPro/GoPRO_INR/GoPro_test_blur_gamma_ratio_5_steps_20000_dec/"
        data_type: "imgs"
        num_frames: 5

        loader:
            batch_size: 1
            num_workers: 1
